### ISSUE TITLE
Stata Language Server: Python crash

### ISSUE THREAD

**Issue by QuangPhan1303** [HankBO/stata-language-server#7]
How can i fix this error? Many thanks.

The /usr/bin/python3 server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by HankBO** [comment]
> How can i fix this error? Many thanks.
> 
> The /usr/bin/python3 server crashed 5 times in the last 3 minutes. The server will not be restarted.

Can you provide more details about your issue? Or upload any screenshot about the error?

**Comment by QuangPhan1303** [comment]
I found the output of this error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/__main__.py", line 4, in <module>
    from .server import stata_server
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/server.py", line 1, in <module>
    import server.utils as utils
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/utils.py", line 2, in <module>
    from pygls.lsp.types import (CompletionItem, CompletionList,
ModuleNotFoundError: No module named 'pygls.lsp.types'
[Info  - 8:53:07 AM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/__main__.py", line 4, in <module>
    from .server import stata_server
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/server.py", line 1, in <module>
    import server.utils as utils
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/utils.py", line 2, in <module>
    from pygls.lsp.types import (CompletionItem, CompletionList,
ModuleNotFoundError: No module named 'pygls.lsp.types'
[Info  - 8:53:09 AM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/__main__.py", line 4, in <module>
    from .server import stata_server
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/server.py", line 1, in <module>
    import server.utils as utils
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/utils.py", line 2, in <module>
    from pygls.lsp.types import (CompletionItem, CompletionList,
ModuleNotFoundError: No module named 'pygls.lsp.types'
[Info  - 8:53:11 AM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/__main__.py", line 4, in <module>
    from .server import stata_server
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/server.py", line 1, in <module>
    import server.utils as utils
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/utils.py", line 2, in <module>
    from pygls.lsp.types import (CompletionItem, CompletionList,
ModuleNotFoundError: No module named 'pygls.lsp.types'
[Info  - 8:53:12 AM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/__main__.py", line 4, in <module>
    from .server import stata_server
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/server.py", line 1, in <module>
    import server.utils as utils
  File "/home/quangphan/.vscode/extensions/hai-bo.stata-language-server-1.1.2/server/utils.py", line 2, in <module>
    from pygls.lsp.types import (CompletionItem, CompletionList,
ModuleNotFoundError: No module named 'pygls.lsp.types'
[Error - 8:53:13 AM] Connection to server got closed. Server will not be restarted.

I had tried to reinstall pygls but it has still not worked.

**Comment by QuangPhan1303** [comment]
The error appeared when I used pygls 1.0.0. The problem was solved after downgraded to version 0.11.3
